// Black-box declaration for the analog macro `cmp_2stage_clk`.
// Generated by mbg.outputs — there is no behavioural model here;
// the implementation is the GDS, and this exists so RTL and
// LibreLane can instantiate the block.
//
// Supplies (2): vdd, vss
// Signal pins are declared `inout`: a SPICE netlist records
// connectivity, not direction, so anything else would be a guess.

`timescale 1ns / 1ps
`default_nettype none

(* blackbox *)
module cmp_2stage_clk (
    vdd,
    vss,
    inp,
    inm,
    clk,
    out
);

    inout  vdd;
    inout  vss;
    inout  inp;
    inout  inm;
    inout  clk;
    inout  out;

endmodule

`default_nettype wire
