// Black-box declaration for the analog macro `ota_5t`.
// Generated by mbg.outputs — there is no behavioural model here;
// the implementation is the GDS, and this exists so RTL and
// LibreLane can instantiate the block.
//
// Supplies (2): vdd, vss
// Signal pins are declared `inout`: a SPICE netlist records
// connectivity, not direction, so anything else would be a guess.

`timescale 1ns / 1ps
`default_nettype none

(* blackbox *)
module ota_5t (
    vdd,
    vss,
    inp,
    inm,
    out,
    vb
);

    inout  vdd;
    inout  vss;
    inout  inp;
    inout  inm;
    inout  out;
    inout  vb;

endmodule

`default_nettype wire
