// Black-box declaration for the analog macro `rc_filter`.
// Generated by mbg.outputs — there is no behavioural model here;
// the implementation is the GDS, and this exists so RTL and
// LibreLane can instantiate the block.
//
// Supplies (1): vss
// Signal pins are declared `inout`: a SPICE netlist records
// connectivity, not direction, so anything else would be a guess.

`timescale 1ns / 1ps
`default_nettype none

(* blackbox *)
module rc_filter (
    vin,
    vout,
    vss
);

    inout  vin;
    inout  vout;
    inout  vss;

endmodule

`default_nettype wire
