"""Chip-level integration: collect generated modules into a LibreLane run.

Each module produced by the layout flow ships a `<cell>.views.json` manifest
listing its GDS, LEF, Liberty, Verilog, netlists and reports. This module reads
those manifests and produces everything a LibreLane macro integration needs:

    <top>.v              top-level Verilog instantiating every module
    config.json          LibreLane configuration with the macros declared
    info.yaml            Chipathon project metadata
    lvs_config.json      per-module and integration LVS configuration
    macros.json          macro placement summary

LibreLane itself is invoked only if it is installed; when it is not, everything
above is still generated and the run is reported as NOT RUN rather than passed.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence

__all__ = ["Module", "discover_modules", "write_top_verilog", "write_librelane_config",
           "write_info_yaml", "write_lvs_config", "run_librelane", "integrate"]


@dataclass
class Module:
    """One generated block and the views it provides."""
    cell: str
    directory: str
    files: Dict[str, Optional[str]] = field(default_factory=dict)
    ports: List[Dict[str, str]] = field(default_factory=list)

    def path(self, view: str) -> Optional[str]:
        rel = self.files.get(view)
        if not rel:
            return None
        p = os.path.join(self.directory, rel)
        return p if os.path.isfile(p) else None

    @property
    def port_names(self) -> List[str]:
        return [p["name"] for p in self.ports]

    def missing(self, needed: Sequence[str]) -> List[str]:
        return [v for v in needed if not self.path(v)]


def discover_modules(search_roots: Sequence[str]) -> List[Module]:
    """Find every module that published a views manifest."""
    found: List[Module] = []
    for root in search_roots:
        if not os.path.isdir(root):
            continue
        for dirpath, _dirs, files in os.walk(root):
            for fn in files:
                if not fn.endswith(".views.json"):
                    continue
                try:
                    data = json.load(open(os.path.join(dirpath, fn)))
                except Exception:
                    continue
                found.append(Module(cell=data.get("cell") or fn[:-11],
                                    directory=dirpath,
                                    files=data.get("files", {}),
                                    ports=data.get("ports", [])))
    found.sort(key=lambda m: m.cell)
    return found


def write_top_verilog(top: str, modules: Sequence[Module], outdir: str, *,
                      shared: Sequence[str] = ("vdd", "vss")) -> str:
    """Top level instantiating each module.

    Supply pins are tied to shared top-level supplies; every other pin is
    exposed as a top-level port named `<cell>_<pin>`, because two analog blocks
    having a pin called `out` does not mean they should be wired together.
    """
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, f"{top}.v")

    shared_l = [s.lower() for s in shared]
    top_ports: List[str] = list(shared)
    inst_lines: List[str] = []

    for m in modules:
        conns = []
        for p in m.ports:
            name, direction = p["name"], p.get("direction", "inout")
            if name.lower() in shared_l or direction in ("power", "ground"):
                target = name if name.lower() in shared_l else (
                    shared[0] if direction == "power" else shared[1])
            else:
                target = f"{m.cell}_{name}"
                if target not in top_ports:
                    top_ports.append(target)
            conns.append(f"        .{name}({target})")
        inst_lines.append(
            f"    {m.cell} u_{m.cell} (\n" + ",\n".join(conns) + "\n    );")

    decls = "\n".join(f"    inout  {p};" for p in top_ports)
    plist = ",\n".join(f"    {p}" for p in top_ports)
    with open(path, "w") as f:
        f.write(
            f"// Chip-level integration for `{top}`.\n"
            f"// Generated by mbg.integrate from each module's views manifest.\n"
            f"//\n"
            f"// {len(modules)} module(s): {', '.join(m.cell for m in modules) or 'none'}\n"
            f"// Supplies {list(shared)} are shared. Every other pin is exposed as\n"
            f"// <cell>_<pin>: two blocks both having a pin called `out` is not a\n"
            f"// reason to connect them, so nothing is joined implicitly.\n\n"
            f"`timescale 1ns / 1ps\n`default_nettype none\n\n"
            f"module {top} (\n{plist}\n);\n\n{decls}\n\n"
            + "\n\n".join(inst_lines) + "\n\nendmodule\n\n`default_nettype wire\n")
    return path


def write_librelane_config(top: str, modules: Sequence[Module], outdir: str, *,
                           pdk: str = "gf180mcuD",
                           std_cell_library: str = "gf180mcu_fd_sc_mcu7t5v0",
                           die_margin: float = 20.0) -> str:
    """LibreLane configuration declaring each block as a hard macro."""
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, "config.json")

    def rel(p: Optional[str]) -> Optional[str]:
        return os.path.relpath(p, outdir) if p else None

    macros = {}
    for m in modules:
        gds, lef, lib = m.path("gds"), m.path("lef"), m.path("lib")
        if not (gds and lef):
            continue                       # a macro without a LEF cannot be placed
        entry = {
            "gds": [rel(gds)],
            "lef": [rel(lef)],
            "instances": {f"u_{m.cell}": {"location": [0, 0], "orientation": "N"}},
        }
        if lib:
            entry["lib"] = {"*": [rel(lib)]}
        if m.path("pex_spice") or m.path("sch_spice"):
            entry["spice"] = [rel(m.path("pex_spice") or m.path("sch_spice"))]
        macros[m.cell] = entry

    cfg = {
        "DESIGN_NAME": top,
        "VERILOG_FILES": [f"dir::{top}.v"],
        "PDK": pdk,
        "STD_CELL_LIBRARY": std_cell_library,
        "CLOCK_PORT": None,
        "CLOCK_PERIOD": 10,
        "MACROS": macros,
        "FP_SIZING": "absolute",
        "DIE_AREA": _die_area(modules, die_margin),
        "PL_TARGET_DENSITY_PCT": 40,
        "RUN_LINTER": False,
        "RUN_CVC": False,
        "//": (f"Generated by mbg.integrate. {len(macros)} macro(s) declared. "
               f"Analog blocks are hard macros: they carry no timing arcs, so "
               f"CLOCK_PORT is null and STA over them is not meaningful."),
    }
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2, sort_keys=True)
        f.write("\n")
    return path


def _die_area(modules: Sequence[Module], margin: float) -> List[float]:
    """A die big enough for the macros laid side by side, plus margin."""
    import re
    total_w, max_h = 0.0, 0.0
    for m in modules:
        lef = m.path("lef")
        if not lef:
            continue
        mm = re.search(r"SIZE\s+([\d.]+)\s+BY\s+([\d.]+)", open(lef).read())
        if mm:
            total_w += float(mm.group(1)) + margin
            max_h = max(max_h, float(mm.group(2)))
    if total_w <= 0:
        total_w, max_h = 100.0, 100.0
    return [0.0, 0.0, round(total_w + margin, 3), round(max_h + 2 * margin, 3)]


def write_info_yaml(top: str, modules: Sequence[Module], outdir: str, *,
                    title: str, team: str, description: str,
                    discord: str = "",
                    lvs_configs: Optional[Sequence[str]] = None) -> str:
    """Chipathon project metadata."""
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, "info.yaml")
    cfgs = list(lvs_configs or [f"lvs_config_{m.cell}.json" for m in modules])
    lines = [
        "# ----- ------ ----- ----- ------ ----- ----- ------ -----",
        "# Chipathon 2026: Project configuration",
        "# LICENSE: Apache License Version 2.0",
        "# http://www.apache.org/licenses/",
        "# ----- ------ ----- ----- ------ ----- ----- ------ -----",
        "#",
        "# Generated by mbg.integrate — regenerate rather than hand-editing.",
        "",
        "project:",
        f'  title: "{title}"',
        f'  team: "{team}"',
        f'  discord: "{discord}"',
        f'  description: "{description}"',
        "  # Relative paths to the lvs_config.json files used for integration.",
        "  lvs_config:",
    ]
    lines += [f'    - "{c}"' for c in cfgs] or ['    []']
    lines += ["", "  modules:"]
    for m in modules:
        lines.append(f'    - name: "{m.cell}"')
        lines.append(f'      pins: [{", ".join(m.port_names)}]')
    return _write(path, "\n".join(lines) + "\n")


def write_lvs_config(module: Module, outdir: str, *,
                     std_cell_library: str = "gf180mcu_fd_sc_mcu7t5v0",
                     uprj_prefix: str = "$UPRJ_ROOT",
                     repo_root: Optional[str] = None) -> str:
    """LVS configuration for one module, in the Chipathon layout."""
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, f"lvs_config_{module.cell}.json")

    def uprj(p: Optional[str]) -> str:
        if not p:
            return ""
        if repo_root:
            try:
                return f"{uprj_prefix}/{os.path.relpath(p, repo_root)}"
            except ValueError:
                pass
        return p

    cfg = {
        "STD_CELL_LIBRARY": std_cell_library,
        "INCLUDE_CONFIGS": ["$PDK_ROOT/tech/$PDK/lvs_config.base.json"],
        "TOP_SOURCE": module.cell,
        "TOP_LAYOUT": "$TOP_SOURCE",
        "EXTRACT_FLATGLOB": [""],
        "EXTRACT_ABSTRACT": [""],
        "LVS_FLATTEN": [""],
        "LVS_NOFLATTEN": [""],
        "LVS_IGNORE": [""],
        "LVS_SPICE_FILES": [uprj(module.path("sch_spice"))],
        "LVS_VERILOG_FILES": [""],
        "LAYOUT_FILE": uprj(module.path("gds")),
    }
    return _write(path, json.dumps(cfg, indent=2) + "\n")


def _write(path: str, text: str) -> str:
    with open(path, "w") as f:
        f.write(text)
    return path


def run_librelane(config_path: str, *, timeout: int = 7200) -> Dict[str, object]:
    """Invoke LibreLane if it is installed.

    Returns a status dict. When LibreLane is absent the status is NOT RUN —
    never PASS. Generating a configuration is not the same as running the flow.
    """
    exe = shutil.which("librelane") or shutil.which("openlane")
    if exe is None:
        try:
            import librelane  # noqa: F401
            cmd = ["python3", "-m", "librelane", config_path]
        except ImportError:
            return {"status": "NOT RUN", "reason":
                    "LibreLane is not installed (no `librelane`/`openlane` on PATH "
                    "and no importable module). The configuration was generated and "
                    "can be run elsewhere.", "config": config_path}
    else:
        cmd = [exe, config_path]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                           cwd=os.path.dirname(os.path.abspath(config_path)))
    except subprocess.TimeoutExpired:
        return {"status": "FAIL", "reason": f"timed out after {timeout}s"}
    except Exception as e:
        return {"status": "FAIL", "reason": f"{type(e).__name__}: {e}"}
    return {"status": "PASS" if r.returncode == 0 else "FAIL",
            "returncode": r.returncode,
            "stdout_tail": (r.stdout or "")[-4000:],
            "stderr_tail": (r.stderr or "")[-4000:]}


def integrate(top: str, search_roots: Sequence[str], outdir: str, *,
              title: str = "AI-generated analog blocks",
              team: str = "", description: str = "",
              discord: str = "", pdk: str = "gf180mcuD",
              repo_root: Optional[str] = None,
              run: bool = False, verbosity: int = 1) -> Dict[str, object]:
    """Discover modules and generate the full integration deliverable set."""
    os.makedirs(outdir, exist_ok=True)
    modules = discover_modules(search_roots)
    if verbosity:
        print(f"  [INTEGRATE] {len(modules)} module(s) discovered")
        for m in modules:
            miss = m.missing(["gds", "lef", "lib", "verilog", "sch_spice"])
            print(f"     {m.cell:24s} pins={len(m.ports):2d}"
                  + (f"  missing: {', '.join(miss)}" if miss else "  all views present"))
    if not modules:
        return {"modules": [], "status": "NOT RUN",
                "reason": f"no *.views.json found under {list(search_roots)}"}

    out: Dict[str, object] = {"modules": [m.cell for m in modules]}
    out["top_verilog"] = write_top_verilog(top, modules, outdir)
    out["config"] = write_librelane_config(top, modules, outdir, pdk=pdk)
    out["lvs_configs"] = [write_lvs_config(m, outdir, repo_root=repo_root)
                          for m in modules]
    out["info_yaml"] = write_info_yaml(
        top, modules, outdir, title=title, team=team,
        description=description or f"Integration of {len(modules)} generated analog blocks",
        discord=discord,
        lvs_configs=[os.path.basename(p) for p in out["lvs_configs"]])
    out["macros"] = _write(os.path.join(outdir, "macros.json"),
                           json.dumps({m.cell: {"dir": m.directory,
                                                "pins": m.port_names}
                                       for m in modules}, indent=2, sort_keys=True) + "\n")
    # Native assembly: produce the integration deliverables directly, so the
    # full view set exists whether or not LibreLane is installed. When
    # LibreLane does run it supersedes this with a proper PDN and floorplan.
    try:
        asm = assemble_gds(top, modules, outdir, verbosity=verbosity)
        out["gds"] = asm["gds"]
        out["placements"] = asm["placements"]
        out["ports"] = asm["ports"]
        out["sch_spice"] = write_top_spice(top, modules, outdir, asm["ports"])
        out.update(_signoff_top(top, asm, outdir, verbosity=verbosity))
    except Exception as e:
        out["assembly"] = {"status": "FAIL", "reason": f"{type(e).__name__}: {e}"}
        if verbosity:
            print(f"  [INTEGRATE] assembly FAILED: {type(e).__name__}: {e}")

    out["librelane"] = run_librelane(out["config"]) if run else {
        "status": "NOT RUN", "reason": "run=False; configuration generated only"}
    if verbosity:
        print(f"  [INTEGRATE] LibreLane: {out['librelane']['status']}"
              + (f" — {out['librelane'].get('reason','')}"
                 if out["librelane"].get("reason") else ""))
    return out


def _signoff_top(top: str, asm: Dict[str, object], outdir: str, *,
                 verbosity: int = 1) -> Dict[str, object]:
    """LEF, LIB, DRC, LVS and PEX for the assembled top.

    Each step is independent: a missing tool records NOT RUN for that view and
    leaves the rest alone. Nothing here reports PASS on the strength of a file
    merely existing.
    """
    from mbg.outputs import classify_ports, write_lef, write_lib
    from mbg.checks import run_drc, run_lvs, run_pex

    gds = asm["gds"]
    res: Dict[str, object] = {}
    directions = {p["name"]: p.get("direction", "inout")
                  for p in asm["ports"]}
    specs = classify_ports(list(directions), directions)

    res["lef"] = write_lef(gds, top, outdir)
    res["lib"] = write_lib(top, specs, outdir)

    try:
        res["drc"] = run_drc(gds, cell_name=top, workdir=outdir)
    except Exception as e:
        res["drc"] = {"clean": False, "summary": f"DRC ERROR: {e}",
                      "error_count": -1}
    try:
        res["lvs"] = run_lvs(gds, os.path.join(outdir, f"{top}.spice"),
                             cell_name=top, workdir=outdir)
    except Exception as e:
        res["lvs"] = {"match": False, "summary": {"message": f"LVS ERROR: {e}"}}
    try:
        res["pex"] = run_pex(gds, cell_name=top, workdir=outdir)
    except Exception as e:
        res["pex"] = {"ok": False, "summary": f"PEX ERROR: {e}"}

    res["floating_grounds"] = _floating_grounds(outdir, top)
    res["lvs_note"] = (
        "Top-level LVS of mutually disconnected macros is expected to be "
        "inconclusive: with no PDN and no inter-block nets, the blocks are "
        "symmetric islands joined only by the substrate, and netgen cannot "
        "assign net classes uniquely. Each macro's OWN LVS is authoritative "
        "and is reported per module. Run the LibreLane flow (run=True) for a "
        "chip-level result — its power grid and I/O break the symmetry.")
    if verbosity:
        drc = res.get("drc") or {}
        lvs = (res.get("lvs") or {}).get("summary") or {}
        print(f"  [INTEGRATE] top DRC: {drc.get('summary', '?')} | "
              f"LVS: {lvs.get('message', lvs) if isinstance(lvs, dict) else lvs}")
        for n in res["floating_grounds"]:
            print(f"  [INTEGRATE] WARNING: {n} — a pin declared as ground that "
                  f"is NOT tied to the substrate. Magic split it off as its own "
                  f"net, so it is floating, not grounded.")
    return res


def _floating_grounds(outdir: str, top: str) -> List[str]:
    """Ground pins the layout did not actually connect to the substrate.

    Magic uniquifies a second net carrying an already-used label, so a
    ``vss_uq2`` in the extracted netlist means some block's "ground" is not
    tied to the substrate at all. That is a real defect and specific enough to
    name, rather than letting it surface as "top-level pin matching failed".
    """
    path = os.path.join(outdir, f"{top}_extracted_flat.spice")
    if not os.path.isfile(path):
        return []
    found: List[str] = []
    with open(path) as f:
        for line in f:
            low = line.lower()
            if not (low.startswith(".subckt") or low.startswith("+")):
                continue
            for tok in line.split():
                if re.match(rf"^{GLOBAL_GROUND}_uq\d+$", tok) and tok not in found:
                    found.append(tok)
    return found


# ── native assembly (no LibreLane required) ────────────────────────────

GLOBAL_GROUND = "vss"


def _module_pin_name(module: "Module", pin: str,
                     direction: str = "inout") -> str:
    """Top-level name for one module pin.

    Ground is **global**: every macro sits in the same p-substrate, and each
    one ties its ground to that substrate, so those nets are physically one
    net whether or not a wire is drawn between them. Magic extracts them as
    one, so the schematic has to say so too — naming them separately made LVS
    fail with "top-level pin matching failed" for a merge that is real.

    Everything else, supplies included, is prefixed with its cell. Two blocks
    both having a pin called ``out`` is not a reason to join them, and nothing
    here draws a power grid, so a shared ``vdd`` would describe a net that
    does not exist in the layout. (The LibreLane flow does build a PDN; that
    is what `run=True` and the generated config are for.)
    """
    if direction == "ground":
        return GLOBAL_GROUND
    return f"{module.cell}_{pin}"


def _module_pin_names(module: "Module") -> List[str]:
    """Top-level net for each of a module's pins, in port order."""
    return [_module_pin_name(module, p["name"], p.get("direction", "inout"))
            for p in module.ports]


def assemble_gds(top: str, modules: Sequence["Module"], outdir: str, *,
                 gap: float = 20.0, verbosity: int = 1) -> Dict[str, object]:
    """Merge every module GDS into one top cell, in a row, and label its pins.

    Returns {"gds": path, "ports": [...], "placements": {...}}.
    """
    import gdstk

    os.makedirs(outdir, exist_ok=True)
    lib = gdstk.Library(name=top, unit=1e-6, precision=5e-9)
    topcell = gdstk.Cell(top)
    lib.add(topcell)

    seen: set = set()
    placements: Dict[str, Dict[str, float]] = {}
    ports: List[Dict[str, str]] = []
    cursor = 0.0

    for m in modules:
        gds = m.path("gds")
        if not gds:
            continue
        src = gdstk.read_gds(gds)
        cells = list(src.cells)
        names = {c.name for c in cells}
        clash = names & seen
        if clash:
            raise ValueError(
                f"cell-name collision importing {gds}: {sorted(clash)}. "
                f"Two modules built from the same netlist name cannot be "
                f"integrated without renaming one of them.")
        seen |= names

        cell = None
        for c in cells:
            if c.name == m.cell:
                cell = c
                break
        if cell is None:
            top_level = src.top_level()
            if not top_level:
                continue
            cell = top_level[0]
        lib.add(*cells)

        (x0, y0), (x1, y1) = cell.bounding_box()
        dx, dy = cursor - x0, -y0
        topcell.add(gdstk.Reference(cell, origin=(dx, dy)))
        placements[m.cell] = {"x": dx, "y": dy,
                              "w": x1 - x0, "h": y1 - y0}

        # Re-label each pin at its position in the merged frame, so LVS can
        # match the top-level netlist against the assembled layout.
        for lbl in cell.labels:
            for p in m.ports:
                if lbl.text == p["name"]:
                    topcell.add(gdstk.Label(
                        _module_pin_name(m, p["name"],
                                         p.get("direction", "inout")),
                        (lbl.origin[0] + dx, lbl.origin[1] + dy),
                        layer=lbl.layer, texttype=lbl.texttype))
                    break
        for p in m.ports:
            nm = _module_pin_name(m, p["name"], p.get("direction", "inout"))
            if any(q["name"] == nm for q in ports):
                continue        # the shared ground, already declared
            ports.append({"name": nm,
                          "direction": p.get("direction", "inout")})
        cursor += (x1 - x0) + gap

    path = os.path.join(outdir, f"{top}.gds")
    lib.write_gds(path)
    if verbosity:
        print(f"  [INTEGRATE] assembled {len(placements)} macro(s) -> {path}")
    return {"gds": path, "ports": ports, "placements": placements}


def write_top_spice(top: str, modules: Sequence["Module"], outdir: str,
                    ports: Sequence[Dict[str, str]]) -> str:
    """Schematic netlist for the assembled top.

    Each module's own subcircuit definition is inlined so the file stands on
    its own for LVS; the top simply instantiates them side by side.
    """
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, f"{top}.spice")
    body: List[str] = []
    defs: List[str] = []

    for m in modules:
        sch = m.path("sch_spice")
        if sch:
            text = open(sch).read()
            keep = [ln for ln in text.splitlines()
                    if not ln.strip().lower().startswith((".lib", ".include"))]
            defs.append("\n".join(keep).strip())
        pins = " ".join(_module_pin_names(m))
        body.append(f"X{m.cell} {pins} {m.cell}")

    names = " ".join(p["name"] for p in ports)
    with open(path, "w") as f:
        f.write(f"* Chip-level schematic for `{top}`.\n"
                f"* Generated by mbg.integrate — {len(modules)} macro(s), placed\n"
                f"* side by side with no interconnect.\n"
                f"*\n"
                f"* Ground is one global net ({GLOBAL_GROUND}): the macros share a\n"
                f"* p-substrate and each ties its ground to it, so those nets are\n"
                f"* physically one whether or not a wire is drawn. Every other\n"
                f"* pin, vdd included, is <cell>_<pin> — nothing else is joined,\n"
                f"* because nothing else is joined in the layout either.\n\n"
                + "\n\n".join(defs) + "\n\n"
                + f".subckt {top} {names}\n"
                + "\n".join(f"  {b}" for b in body)
                + f"\n.ends\n")
    return path
